Repository FatecCoderHood/4_Front, pull requests merged in 2025-04, with the labels that each got.

#17 fix <VIS-67> Correção de bugs e melhoria de experiência
  src/pages/Map.vue
Labels: bug, enhancement

#23 chore <VIS-97> [Frontend] Ajustar tela de importação de .GeoJson
  components.d.ts
  src/components/Farms/FarmDeleteDialog.vue
  src/components/Farms/FarmForm.vue
  src/components/Farms/FarmList.vue
  src/components/Farms/FarmTableActions.vue
  src/components/Farms/GeoJsonProcessor.vue
  src/pages/Farms.vue
  src/types/farms.ts
Labels: enhancement

#21 chore <VIS-91> [Frontend] Implementar tela de listagem de inspeções
  src/components/FarmsMenu.vue
  src/pages/Map.vue
Labels: enhancement

#27 fix <VIS-91> [Frontend] Implementar tela de listagem de inspeções
  components.d.ts
  src/components/FarmsMenu.vue
  src/components/Map/DrawingPanel.vue
  src/components/Map/FarmsMenu.vue
  src/components/Map/GeoJSONLayer.vue
  src/components/Map/MapControls.vue
  src/pages/Map.vue
  src/types/farms.ts
Labels: bug, enhancement

#26 <style>(VIS-86): Redesign da listagem de fazendas aplicado
  src/components/Farms/FarmList.vue
  src/components/Farms/FarmTableActions.vue
  src/components/Farms/FarmViewDialog.vue
  src/pages/Farms.vue
Labels: enhancement

#28 feat <VIS-92> [Frontend] Implementar tela de avaliação (Aprovado | Re…
  components.d.ts
  src/components/Map/FarmsMenu.vue
  src/components/Map/StatusActions.vue
  src/pages/Map.vue
Labels: functionality

#31 chore <VIS-92> [Front-end] Implementação de atualização de status
  src/pages/Map.vue
Labels: enhancement
