Repository FatecCoderHood/4_Front, pull requests merged in 2025-05, with the labels that each got.

#37 <refactor> <style>(VIS-146): Redesign da tela de Gestão de Usuários a…
  src/components/Users/UserDeleteDialog.vue
  src/components/Users/UserForm.vue
  src/components/Users/UserList.vue
  src/components/Users/UserTableActions.vue
  src/components/users/EditUserDrawer.vue
  src/components/users/RegisterUserDrawer.vue
  src/pages/Users.vue
Labels: enhancement

#38 feat <VIS-149> [Feature]: Mudar o relacionamento dos talhões
  components.d.ts
  src/components/Map/FarmsMenu.vue
  src/components/Map/StatusActions.vue
  src/pages/Map.vue
  src/types/farms.ts
Labels: enhancement

#39 <style>(VIS-144): Aplicado redesign do wizard de cadastro e edição de…
  src/components/Farms/FarmForm.vue
  src/components/Farms/FarmSummary.vue
  src/components/Farms/StepperFooter.vue
Labels: style

#40 <feat> (VIS-148): Adicionada a feature que carrega as cidades dinamic…
  src/components/Farms/FarmForm.vue
Labels: functionality

#41 <feat>(VIS-117): Criada a pagina de Dashboard e aplicada com os dados…
  package-lock.json
  package.json
  src/components/AppHeader.vue
  src/components/Dashboard/DashboardBody.vue
  src/components/Dashboard/DonutChart.vue
  src/pages/Dashboard.vue
  src/pages/Users.vue
Labels: functionality

#50 hotfix <VIS-128> Correção do front .tif
  components.d.ts
  package-lock.json
  package.json
  src/components/Farms/FarmUploadTiff.vue
  src/components/Map/TiffProcessor.vue
  src/components/Map/WeedsOverlay.vue
  src/pages/Farms.vue
  src/pages/Map.vue
Labels: enhancement, functionality

#54 Revert "feat (VIS-129): Implementação do componente de Upload Drawer com barr…"
  components.d.ts
  src/components/Farms/UploadStatusDrawer.vue
  src/pages/Farms.vue
Labels: bug
